### ISSUE TITLE
Release jar packaged artifact

### ISSUE THREAD

**Issue by WonderCsabo** [square/assertj-android#110]
I looked at the snapshot release and i see it only comes with AAR packaging. Can we get an artifact with simple jar packaging? This way this library could be easily used in eclipse, where there is no way to use AARs. Actually i see no reason to package this library as an AAR, since this contains only classes, no resources, also its nature fits a jar much more.

**Comment by pendext** [comment]
Not sure if this is everything that is necessary for creating the jars during the gradle build: https://github.com/square/assertj-android/pull/149

**Comment by kingargyle** [comment]
We used the patch ing #149 and it works well to produce the necessary jar versions so we can use it in our maven builds and with the maven-surefire-plugin and robolectric.  The AARs are not added to the classpath if you specify a test scope, and if you specify them as a normal dependency they get included in the APK.
