### ISSUE TITLE
Support for API 21 and latest gradle and android gradle plugin

### ISSUE THREAD

**Issue by emartynov** [square/assertj-android#140]
I started small contribution and found that project still use RC for API 2, older gradle and android gradle plugin

**Comment by ararog** [comment]
You is right, everything goes well if I switch from com.android.support:appcompat-v7:21.+ to com.android.support:appcompat-v7:20.+  

Right now gradle build doesn't run if we use appcompat version 21.+ and assertj-android together.

**Comment by JakeWharton** [comment]
This is fixed.
