### ISSUE TITLE
Running assertj-android in java module with robolectric

### ISSUE THREAD

**Issue by fabiocarballo** [square/assertj-android#146]
Hi,

Is there are any know way to run assertj-android along with robolectric in a java test module? I'm creating a separate module just to run robolectric tests, but when using assertj-android there are some missing dependencies on the android-support:support-annotations.

Thank you!

**Comment by JakeWharton** [comment]
There is no way to do this currently. #110 is tracking publishing as a jar or simply wait until first-party unit testing support ships in 1.1 of the Gradle Android plugin.
