### ISSUE TITLE
error: cannot access TaskStackBuilder

### ISSUE THREAD

**Issue by AshwinNBhanushali** [square/assertj-android#147]
I am getting compilation error while using the lib below is the error 

E:\Sync\app\src\androidTest\java\kamlesh\sync\activities\DashboardTest.java:31: error: cannot access TaskStackBuilder
           assertThat(activity.spinner).isGone();
           ^
  class file for android.app.TaskStackBuilder not found

I am using Android Studio 1.0.2.
Here is the screenshot
![screenshot 3](https://cloud.githubusercontent.com/assets/1049452/5915902/180c36f6-a631-11e4-9f31-16f5d48c2eb5.png)

**Comment by JakeWharton** [comment]
What version of Android are you compiling with?

**Comment by AshwinNBhanushali** [comment]
I am compiling with version 4.2(Jellybean)

**Comment by JakeWharton** [comment]
Because of the nature of this project, you need to compile with the latest version of the platform SDK. You can still have minimum and target API levels which are older and lint will protect you from calling too-new methods.
