### ISSUE TITLE
Rename ANDROID.assertThat to ANDROID.assertThatAndroid

### ISSUE THREAD

**Issue by mogronalol** [square/assertj-android#148]
If I want to use assertj and this library in one class, it would be nice if I could static import everything.  So I would have along the lines of:

```java
assertThatAndroid(textView).hasText("foo")
assertThat(someList).containsExactly("one", "two")
```

I just find it a little more expression that having to write:

```java
ANDROID.assertThat(textView).hasText("foo")
assertThat(someList).containsExactly("one", "two")
```

Perhaps I'm being a little pedantic, but I'm wondering if this is a good idea or not?  If so I can issue a pull request, or if it will be annoying as it will be a breaking change for everyone.

**Comment by JakeWharton** [comment]
```java
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.android.api.Assertions.assertThat;
```

**Comment by mogronalol** [comment]
For some reason my ide wasn't letting me do this with alt + enter but a
manual static import is fine. Thanks.
