### ISSUE TITLE
Dependency Resolution Issue

### ISSUE THREAD

**Issue by jophde** [square/assertj-android#158]
I am trying to add the Google Play Services module.  Getting this error

    Error:A problem occurred configuring project ':mobile'.
> Could not resolve all dependencies for configuration ':mobile:_debugAndroidTestCompile'.
   > Could not find com.google.android.gms:play-services:5.2.08.
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/android/gms/play-services/5.2.08/play-services-5.2.08.pom
         https://jcenter.bintray.com/com/google/android/gms/play-services/5.2.08/play-services-5.2.08.jar
         https://repo1.maven.org/maven2/com/google/android/gms/play-services/5.2.08/play-services-5.2.08.pom
         https://repo1.maven.org/maven2/com/google/android/gms/play-services/5.2.08/play-services-5.2.08.jar
         file:/Users/jophde/.android-sdk/extras/android/m2repository/com/google/android/gms/play-services/5.2.08/play-services-5.2.08.pom
         file:/Users/jophde/.android-sdk/extras/android/m2repository/com/google/android/gms/play-services/5.2.08/play-services-5.2.08.jar
         file:/Users/jophde/.android-sdk/extras/google/m2repository/com/google/android/gms/play-services/5.2.08/play-services-5.2.08.pom
         file:/Users/jophde/.android-sdk/extras/google/m2repository/com/google/android/gms/play-services/5.2.08/play-services-5.2.08.jar
     Required by:
         Surprise:mobile:unspecified > com.squareup.assertj:assertj-android-play-services:1.0.0

5.2.08 does not seem to be in the local Gooogle support repo on my machine any longer.

**Comment by JakeWharton** [comment]
Fun. We'll update to 7.0 next week.

**Comment by JakeWharton** [comment]
848bb19f58e1761d20141e0354c390fb7707b178
