### ISSUE TITLE
asserts using isEqualToIgnoringGivenFields or isEqualToComparingFieldByField doesnt work properly

### ISSUE THREAD

**Issue by otoniel-isidoro-sofist** [square/assertj-android#162]
I have the following objects: 

actual:  
UserInfo{userId='97ed99c1-13d9-4886-99f0-15e3e309bfac', appInstallId='f9d6abaf-e3e4-4281-9ad2-9d8083bd5936', scenarioId=18, advertisingId='803cef82-00af-4c0d-b76e-4f438118ec71', androidId='5ec1103ef436f4f6', imei='null', pushToken='null', platformAccountEmail='[]', deviceSystemName='ANDROID', deviceSystemVersion='5.1', deviceCountry='US', deviceLanguage='en', deviceTimezone='-3', deviceManufacturer='unknown', deviceModel='Android SDK built for x86', appInstalledAt=1432823697421, appVersion='0.11.3', appSdkVersion='0.11.4', tags=null}

expected: 
UserInfo{userId='97ed99c1-13d9-4886-99f0-15e3e309bfac', appInstallId='f9d6abaf-e3e4-4281-9ad2-9d8083bd5936', scenarioId=17, advertisingId='803cef82-00af-4c0d-b76e-4f438118ec71', androidId='5ec1103ef436f4f6', imei='null', pushToken='APA91bE_u2RlHz9HmiK68-RQfZcDTU_Wzsf7xZgYPp4orGmsrs5uXZ1tmE56TsPiqxfUtGuAxRTuayC0_vmeLiyATEJNaG8z_i6RdP9Oj-rD2zyJp6pFduBrvdO6gjJgAHLup5V5WVIFKzGIkZ3wyBG3WNvKc9Ecpg', platformAccountEmail='[]', deviceSystemName='ANDROID', deviceSystemVersion='5.1', deviceCountry='US', deviceLanguage='en', deviceTimezone='-3', deviceManufacturer='unknown', deviceModel='Android SDK built for x86', appInstalledAt=1432823697421, appVersion='0.11.3', appSdkVersion='0.11.4', tags=null}

When I use isEqualTo assertions the following failure is threw properly:
org.junit.ComparisonFailure: expected:<...d5936', scenarioId=3[3, advertisingId='803cef82-00af-4c0d-b76e-4f438118ec71', androidId='5ec1103ef436f4f6', imei='null', pushToken='APA91bE_u2RlHz9HmiK68-RQfZcDTU_Wzsf7xZgYPp4orGmsrs5uXZ1tmE56TsPiqxfUtGuAxRTuayC0_vmeLiyATEJNaG8z_i6RdP9Oj-rD2zyJp6pFduBrvdO6gjJgAHLup5V5WVIFKzGIkZ3wyBG3WNvKc9Ecpg]', platformAccountEm...> but was:<...d5936', scenarioId=3[4, advertisingId='803cef82-00af-4c0d-b76e-4f438118ec71', androidId='5ec1103ef436f4f6', imei='null', pushToken='null]', platformAccountEm...>

But, when I use isEqualToComparingFieldByField or isEqualToIgnoringGivenFields the test pass even with different values on object's fields.

**Comment by JakeWharton** [comment]
Those features are from AssertJ not AssertJ-Android. Please file a bug on
the AssertJ project.

**Comment by otoniel-isidoro-sofist** [comment]
Ok thx!
