### ISSUE TITLE
Update support-annotations to 22.2.0

### ISSUE THREAD

**Issue by danielgomezrico** [square/assertj-android#164]
I had to include it excluding it because I got:

```
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (22.2.0) and test app (20.0.0) differ.
```

Then my dependencies ended like this and it compiles:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'

    testCompile 'org.assertj:assertj-core:3.0.0'
    androidTestCompile ('com.squareup.assertj:assertj-android:1.0.0'){
        exclude group:'com.android.support', module:'support-annotations'
    }

    compile project(':core')
}
```

Does assertj-android needs an update on that version?

**Comment by JakeWharton** [comment]
This library is not going to track every release of the support annotations. That's infeasible to maintain and would be pointless on our end.

You can either do as you did and exclude the dependency, or force the version using a [resolution strategy][1] (see `force`).

 [1]: https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html

**Comment by danielgomezrico** [comment]
:+1: ok thanks
