### ISSUE TITLE
Android Studio: Each module has to have a unique path

### ISSUE THREAD

**Issue by sberan** [square/assertj-android#174]
After pulling the git repository and opening in Android Studio, I get the following error when trying to sync the project with Gradle:

![Error:The modules 'assertj-android', 'assertj-android-root' point to same directory in the file system.
Each module has to have a unique path.](https://cloud.githubusercontent.com/assets/100066/9936240/93f4066c-5d20-11e5-9d78-47ba2ef26f64.png)

These modules are in different directories, so I'm pretty confused as to why AS would think they are in the same path.

**Comment by JakeWharton** [comment]
This usually is the result of old iml files. Delete them all and reimport.

**Comment by JakeWharton** [comment]
Did that work?

**Comment by sberan** [comment]
sorry - my e-mail notification got buried, trying now.

I wouldn't expect it to work, since it's a freshly cloned project, but I'll
try it!

**Comment by sberan** [comment]
Weird, removing the .iml and reimporting worked.

**Comment by ZhaoKaiQiang** [comment]
it's work for me ,3ks

**Comment by joelcatorpedrojr11** [comment]
step by step please

**Comment by JulianKingman** [comment]
instructions here: http://stackoverflow.com/a/27532990/1198813

**Comment by zhipengyue** [comment]
thank u,very helpful.

**Comment by Senhordim** [comment]
thank man!

**Comment by RahulQorql** [comment]
Deleting IML files and Re-Import fixed the issue.

**Comment by chuwe1** [comment]
That works, good.

**Comment by mima5** [comment]
Where i find the IML files?

**Comment by karimkod** [comment]
@mima5 You can find the iml files on the root directory of your project (if you are working on git, is where you find .git hidden directory)

**Comment by chuwe1** [comment]
@mima5 IML file means a files its suffix is .iml

**Comment by mima5** [comment]
thanks man!

**Comment by kondo0511** [comment]
It works for me thx a lot!

**Comment by elmira-asd** [comment]
you can find them (modules) in `.idea` ---> `modules`

**Comment by ArashYounesi** [comment]
I Updated my android studio and it solved (Now i have android studio V4.0)
None of the above answers helped me
