### ISSUE TITLE
Assert that object is Parcelable

### ISSUE THREAD

**Issue by artem-zinnatullin** [square/assertj-android#177]
What do you think about PR for asserting `Parcelable` implementation? I'd like to contribute that if you don't mind.

`assertThat(object).isParcelable()`, based on https://github.com/artem-zinnatullin/AssertParcelable.

**Comment by JakeWharton** [comment]
Seems out of scope and not in line with what this library is for.

**Comment by artem-zinnatullin** [comment]
ok, np!
