### ISSUE TITLE
Add support for Android 5+ properties

### ISSUE THREAD

**Issue by mpost** [square/assertj-android#188]
For example the properties `elevation`or `translationZ` are not part of the core library.

**Comment by JakeWharton** [comment]
Pull requests are always welcome here! We don't really have the time to work on these at this moment.

**Comment by MichaelEvans** [comment]
@mpost I added elevation/z/translationZ in a PR. Are there any others that you think are significant that I missed?

**Comment by JakeWharton** [comment]
Feel free to comment for others, or file issues for specific ones. Something this general is hard to track and hard to know when it's complete, so I'm going to close.

And thanks @MichaelEvans.

**Comment by mpost** [comment]
Thanks for the additional. I have no others at the moment.
