### ISSUE TITLE
JTextComponentFixture enterText method simulates a qwerty keyboard

### ISSUE THREAD

**Issue by macpoupou** [square/assertj-android#216]
My code is :
```
JTextComponentFixture searchField=myDialog.textBox("SearchField");
searchField.setText("91808093");
```
When it runs it debug mode, it works fine.
In a normal mode, it simulates "(!*)*)(#".

It seems to be the keys of a qwerty keyboard.

**Comment by JakeWharton** [comment]
I think you're looking for AssertJ-Swing not AssertJ-Android.
