### ISSUE TITLE
Error:Conflict with dependency 'com.android.support:support-annotations' in project ':app'. Resolved versions for app (25.2.0) and test app (23.1.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

### ISSUE THREAD

**Issue by azil15** [square/assertj-android#220]
Error:Conflict with dependency 'com.android.support:support-annotations' in project ':app'. Resolved versions for app (25.2.0) and test app (23.1.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

**Comment by JakeWharton** [comment]
This is not a problem with the library but with your build system. You
should look up how to force versions such that the same transitive
dependencies are used. Also you can exclude this transitive dependency from
assertj-android so that the normal one is used.
