### ISSUE TITLE
java.lang.NoSuchMethodError: org.assertj.core.api.AbstractCharSequenceAssert.doesNotContain(Ljava/lang/CharSequence;)

### ISSUE THREAD

**Issue by emartynov** [square/assertj-android#224]
I've updated AssertJ core to 3.9.0 and I got one test failing:

```
        assertThat(viewHolder.date).containsText(" · " + context.getString(R.string.transactions__pending))
```
(where date it `TextView`)
with the message:
```
java.lang.NoSuchMethodError: org.assertj.core.api.AbstractCharSequenceAssert.doesNotContain(Ljava/lang/CharSequence;)Lorg/assertj/core/api/AbstractCharSequenceAssert;

	at org.assertj.android.api.widget.AbstractTextViewAssert.doesNotContainText(AbstractTextViewAssert.java:601)
```

I temporarily fixed it but would be nice to update AssertJ core dependency.

**Comment by JakeWharton** [comment]
Doesn't AssertJ 3 requires Java 8 which makes it prohibitive to use on most
Android versions?

**Comment by emartynov** [comment]
Yes, It requires Java 8. We use it with Robolectric. 

Should AGP 3.0 modify Java8 bytecode for libraries as well?

**Comment by JakeWharton** [comment]
It does, but it can't add the missing APIs in the platform that are
required so your tests would still only work on API 26+.

**Comment by emartynov** [comment]
Clear. I'm closing the issue now. And thinking about a possible solution like having another artefact that fully compatible with Java8.
