### ISSUE TITLE
Error:Execution failed for task ':app:preDebugAndroidTestBuild'. > Conflict with dependency 'com.android.support:support-annotations' in project ':app'. Resolved versions for app (26.1.0) and test app (27.1.1) differ. See https://d.android.com/r/tools/test-apk-dependency-conflicts.html for details.

### ISSUE THREAD

**Issue by vishald19** [square/assertj-android#227]
Anyone Please help me out 
![Screenshot (6)](https://user-images.githubusercontent.com/49333453/55665911-d67fec80-57d1-11e9-9e36-9bf32087741a.png)
with this!!!.Unable to continue with the projects.

**Comment by JakeWharton** [comment]
The error message is pretty clear as to what's happening here. You need to force the support library dependency to be the same version in both your main sources and test sources. You can do this by specifying the same version in both configurations, or by using a resolution strategy like:
```groovy
configurations.all {
  resolutionStrategy {
    eachDependency { details ->
      // Force all of the primary support libraries to use the same version.
      if (details.requested.group == 'com.android.support') {
        details.useVersion versions.supportLibrary
      }
    }
  }
}

**Comment by vishaldevarajan** [comment]
Thank you for your response!!!
