### ISSUE TITLE
Add View tree traversal JQuery inspired assertions

### ISSUE THREAD

**Issue by christopherperry** [square/assertj-android#56]
Was just writing a test and really wanted to write something like:

```JAVA
assertThat(viewGroup).has(textView).withText("fest!");
```

or perhaps

```JAVA
assertThat(viewGroup).has(TextView.class).withText("fest!");
```

is better design.

**Comment by JakeWharton** [comment]
We have no plans for this. It's a fundamental deviation from the core principles of this library (which is itself merely a platform adapter for another library not offering anything along these lines).
